config/routes.rb
Skillsdatabase::Application.routes.draw do
  resources :employees, :except => ['index']

  match '/taggings/skill_tags_cloud', :to => "taggings#skill_tags_cloud"
  match '/taggings/skill_tags_cloud/:limit', :to => "taggings#skill_tags_cloud"

  match '/taggings/skill_tags_group_by_rate/:tag_name', :to => "taggings#skill_tags_group_by_rate"

  match '/taggings/count/:tags_type', :to => "taggings#tags_count"
  match '/taggings/autocomplete', :to => "taggings#autocomplete"

  match '/taggings/:tags_type/:tag_name' , :to => "taggings#tag_query", :constraints => {:tag_name => /[^\/]+/ }

  match '/employees/resume/:id', :to => "employees#resume", :as => 'resume'
  match '/employees/bio/:id', :to => "employees#bio", :as => 'bio'

  match '/auth/:provider/callback', :to => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout
  match '/search', :to => 'employees#search'
  match '/refine', :to => 'employees#refine_search'

  match "/login", :to => "welcome#login"

  root :to => "welcome#index"

end

app/models/employee.rb
class Employee < BaseCouchDocument
  include Memories

  #############
  # Properties
  #############
  property :first_name
  property :last_name
  property :last_name, :alias => :family_name  #playing around with aliases
  property :job_title  #headline
  property :industry
  property :linkedin_url
  property :picture_url
  property :industry_tags do |industry_tag|
                            industry_tag.property :name, String
                          end

  property :skill_tags do |skill_tag|
                          skill_tag.property :name, String
                          skill_tag.property :rate, Integer
                       end

  property :product_tags do |product_tag|
                            product_tag.property :name, String
                         end


  property :phone_number
  property :email

  property :resume
  property :bio
  property :permalink
  property :professional_info
  property :give_gets
  property :interesting_facts
  property :location
  property :num_views, Integer, :default => 0

  timestamps!

  #############
  # Views
  #############
  view_by :first_name, :last_name
  view_by :updated_at, :descending => true
  view_by :id
  view_by :permalink
  view_by :num_views

# Get all employee that have ruby Skills
# Employee.by_skill_tags( :key => 'ruby')
# Get all count of ruby Skills_tag
# Employee.by_skill_tags(:reduce => true, :key => 'ruby')
# Get the count of each Skill tag (Tag Cloud)
# Employee.by_skill_tags(  :reduce => true, :group => true)

  view_by :skill_tags, :map =>
    "function(doc){
      if (doc['couchrest-type'] == 'Employee' && doc['skill_tags']){
        doc.skill_tags.forEach(
          function(skill_tag){
            emit(skill_tag.name, 1);
          }
        );
      }
    };",
    :reduce =>
    "function(keys, values, rereduce){
       return sum(values);
     };"

  view_by :industry_tags, :map =>
    "function(doc){
      if (doc['couchrest-type'] == 'Employee' && doc['industry_tags']){
        doc.industry_tags.forEach(
          function(industry_tag){
            emit(industry_tag.name, 1);
          }
        );
      }
    };",
    :reduce =>
    "function(keys, values, rereduce){
       return sum(values);
     };"

  view_by :product_tags, :map =>
    "function(doc){
      if (doc['couchrest-type'] == 'Employee' && doc['product_tags']){
        doc.product_tags.forEach(
          function(product_tag){
            emit(product_tag.name, 1);
          }
        );
      }
    };",
    :reduce =>
    "function(keys, values, rereduce){
       return sum(values);
     };"

#Employee.by_skill_group_tags(:raw => true)

  view_by :skill_group_tags, :map =>
    "function(doc){
      if (doc['couchrest-type'] == 'Employee' && doc['skill_tags']){
        doc.skill_tags.forEach(
          function(skill_tag){
            rate = skill_tag.rate;
            tag = skill_tag.name;
            if (rate <= 2)
              {
              rate = 'vlow';
              }
            else if (rate >=2 && rate<4)
              {
              rate = 'low';
              }
            else if (rate>=4 && rate<6)
              {
              rate = 'med';
              }
            else if (rate>=6 && rate<8)
              {
              rate = 'high';
              }
            else
              {
              rate = 'vhigh';
              }

          emit([tag,rate], 1);
          }
        );
      }
    };",
    :reduce =>
    "function(keys, values, rereduce){
       return sum(values);
     };"

  ################
  # Observers
  ################
  before_save :generate_permalink, :validate_skill_tags

  def generate_permalink
    self.permalink ||= self.full_name.parameterize
  end

  after_save :extract_differences, :save_index

  def extract_differences
    useless_properties = ['created_at', 'updated_at', 'num_views']

    if self.current_version == 1
      EmployeeEvent.create(:employee => self, :event_type => 'new_employee')
    else
      previous_instance = self.versions[self.previous_version].instance
      changes = []

      self.properties.reject{|property| useless_properties.include? property.to_s}.each do |property|
        changes << property unless self[property] == previous_instance[property]
      end
      if (!changes.empty?)
        EmployeeEvent.create(:employee => self, :changes => changes, :event_type => 'update_profile')
      end
    end
  end

  def save_index
     EmployeeIndexer.add_document(self)
  end

  ################
  # class Methods
  ################
  def self.create_from_hash!(hash)
    if hash['user_info'][:last_job].match(/Razorfish|Globant|Selfemployed/)
      self.create(hash['user_info'][:employee])
    else
      return false
    end
  end

  ################
  # public Methods
  ################
  def validate_skill_tags
    self.skill_tags.map!{|x| x  unless  x.name.blank? }.compact!

  end

  def update_from_linkedin(hash)
    employee = hash['user_info'][:employee]
    Rails.logger.debug(employee)
    self.first_name = employee['first_name']
    self.last_name = employee['last_name']
    self.picture_url = employee['picture_url']
    self.location = employee['location']
    self.industry = employee['industry']
    self.job_title = employee['description']
    save
  end

  def to_param
    self.permalink
  end

  def skill_tags_names(join_str = ', ')
    tags_name_to_s(self.skill_tags,join_str)
  end

  def industry_tags_names(join_str = ', ')
    tags_name_to_s(self.industry_tags,join_str)
  end

  def product_tags_names(join_str = ', ')
    tags_name_to_s(self.product_tags,join_str)
  end

  def full_name
    "#{self.first_name} #{self.last_name}".strip
  end

  def skill_tags_cloud

    tag_cloud = self.skill_tags.select{|x| !x['rate'].blank? }
    tag_cloud.each{ |x| x['rate'] = x['rate'] / 10.0 }

  end
  def self.skill_rate_groups(skill_name)

    vhigh = Employee.by_skill_group_tags(:raw => true, :key => [skill_name,'vhigh'],:reduce => true)
    high = Employee.by_skill_group_tags(:raw => true, :key => [skill_name,'high'],:reduce => true)
    med = Employee.by_skill_group_tags(:raw => true, :key => [skill_name,'med'],:reduce => true)
    low = Employee.by_skill_group_tags(:raw => true, :key => [skill_name,'low'],:reduce => true)
    vlow = Employee.by_skill_group_tags(:raw => true, :key => [skill_name,'vlow'],:reduce => true)

    result = [vlow,low,med,high,vhigh]

    result.map! do |elem|
      !(elem["rows"].empty?)? elem = elem["rows"].first["value"] : elem = 0;
    end

  end
  def self.skill_names_group(skill_name)
    self.by_skill_tags( :key => skill_name).map{|e| e.skill_tags.reject{|t| t[:name] == skill_name }}.flatten.group_by{|x| x[:name]}.map{|k,v| {:name => k,:count => v.count}}.sort{|x,y| y[:count] <=> x[:count]}
  end

  #TODO dry attachments code
  def store_resume(file, filename)
    self.create_attachment({:file => file , :name => filename})
    self.resume = filename
  end

  def store_bio(file, filename)
    self.create_attachment({:file => file , :name => filename})
    self.bio = filename
  end

  def resume_data
    self.read_attachment(self.resume)
  end

  def bio_data
    self.read_attachment(self.bio)
  end

  #################
  # private Methods
  #################
  private

  def tags_name_to_s(tags_arr, join_str)
    tags_arr.map{|tag| tag["name"] }.join(join_str) unless tags_arr.blank?
  end

end

app/controllers/employees_controller.rb
require_dependency 'employee'

class EmployeesController < ApplicationController
  before_filter :find_employee, :only => [:show, :edit, :update, :resume, :bio]
  before_filter :validate_current_user, :only => [:edit, :update]

  def show
  end

  def edit

    @skill_tags_names = @employee.skill_tags_names
    @industry_tags_names = @employee.industry_tags_names
    @product_tags_names = @employee.product_tags_names

  end

  def update
    @employee.store_resume(params[:resume].tempfile, params[:resume].original_filename) if params[:resume]
    @employee.store_bio(params[:bio].tempfile, params[:bio].original_filename) if params[:bio]

    #TODO need refactor
    @employee.skill_tags = []
#    params[:employee]["skill_tags"].each{|tag| @employee.skill_tags << {:name => tag.name.downcase, :rate => tag.rate } }
    @employee.industry_tags = []
    params["industry_tags"].split(", ").each{|tag| @employee.industry_tags << {:name => tag.downcase } }
    @employee.product_tags = []
    params["product_tags"].split(", ").each{|tag| @employee.product_tags << {:name => tag.downcase } }

    # Guard to make sure employee isn't bulk updated, per story #10758361. We use an array of positive values in case we want to add more later.
    updateable_employee_params = params[:employee].select{|key, val| ['email', 'professional_info', 'give_gets', 'interesting_facts'].include? key}
    if @employee.update_attributes(updateable_employee_params)
      redirect_to(root_path, :notice => 'Employee was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def resume
    send_data(@employee.resume_data, :filename => @employee.resume)
  end

  def search
    # Search index based on query
    @index_results = EmployeeIndexer.search(params[:query]) if params[:query]
    
    # Save the search query in couch
    @search = Search.new(:employee => self.current_user, :search => params[:query])
    if !@search.save
      raise "Error saving search"
    end

    # Search DB based on index results.
    @ids = []
    @index_results['results'].each { |doc| @ids << doc['docid'] }
    @results = []
    #by now I'm hitting the DB one by one. I haven't found a better way yet.
    @ids.each do |id| 
      @results << Employee.find(id)
    end
    @matches = @results.compact.count
    @results.compact!      
  
    # Create has set of skills, locations, products, industry - TODO: Move this to couchdb map/reduce if possible!!!!
    logger.debug "Creating locations filter"
    @locations_filter = @results.collect(&:location).uniq.compact

    logger.debug "Creating skills filter"
    @skills_filter = []
    @results.collect(&:skill_tags).each do |skill_tag| 
      skill_tag.each do |skill|
        @skills_filter << skill.name.downcase
      end
    end 
    @skills_filter.uniq!

    logger.debug "Creating products filter"
    @products_filter = []
    @results.collect(&:product_tags).each do |product_tag|
      product_tag.each do |product|
        @products_filter << product.name.downcase
      end
    end
    @products_filter.uniq!

    logger.debug "Creating industry filter"
    @industry_filter = []
    @results.collect(&:industry_tags).each do |industry_tag|
      industry_tag.each do |industry|
        @industry_filter << industry.name.downcase
      end
    end
    @industry_filter.uniq!
    
    # Paginate the search results
    @results = @results.paginate(:page => params[:page], :per_page => 3)    
  end

  def refine_search
    logger.debug "Refining results"
    
    # Create the query string for searching our index
    query_string = ""
    query_string += "__any:(#{params[:query]}) " if params[:query]
    query_string += "skill_tags:(#{params[:skill]})" if params[:skill]
    
    logger.debug "The query string is #{query_string}"
    
    @index_results = EmployeeIndexer.search_by_query(query_string)
    
    logger.debug "Results match type is #{@index_results['results'].class.name}"
    
    @index_results.each do |result|
      logger.debug "Result is #{result}"
    end
    
    logger.debug("Index contains #{@index_results['matches']} results")

    render :nothing => true
  end
    
  def bio
    send_data(@employee.bio_data, :filename => @employee.bio)
  end
  
  private

  def find_employee
    @employee = Employee.find_by_permalink(params[:id])
    
    # Increment the view counter to track 'most viewed' employees
    if (@employee && @employee != current_user)
      @employee.update_attributes(:num_views => @employee.num_views + 1)
    end
    
    @similar_employees = []
    # find similar employees to the one we're viewing
    if (@employee && @employee.skill_tags && !@employee.skill_tags.empty?)
      @skill_tag_query = ""
      @employee.skill_tags.each_with_index do |tag, index| 
        @skill_tag_query << tag.name
        if (index < @employee.skill_tags.length - 1)
          @skill_tag_query << " OR "
        end
      end
      
      # Copied from the search method above...there's gotta be a better way to pull these folks.
      @similar_employees_results = EmployeeIndexer.search(@skill_tag_query) if @skill_tag_query
      @ids = []
      @similar_employees_results['results'].each { |doc| @ids << doc['docid'] }
      @ids.each do |id| 
        @similar_employees << Employee.find(id) unless (id == @employee.id)
      end
      @similar_employees.compact!
    end
    
  end

  def validate_current_user
    redirect_to root_path, :notice => "You don't have permission to complete this task" unless @employee == current_user
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def non_editable_employee_field(fieldname)
    content_tag(:span, @employee.send(fieldname), :class=>"noneditable-field" )
  end
end

app/views/employees/_form.html.erb
<%= javascript_include_tag "autocomplete" %>
<!-- TinyMCE -->
<script type="text/javascript" src="/javascripts/libs/tiny_mce_3.4b3/tiny_mce.js"></script>
<script type="text/javascript">
	tinyMCE.init({
		mode : "textareas",
		theme : "simple",
		width: "400",
		height: "150",
		plugins : "paste",
        theme_advanced_buttons3_add : "pastetext,pasteword,selectall",
        paste_auto_cleanup_on_paste : true
	});
</script>
<!-- /TinyMCE -->
<%= form_for(@employee, :html => {:multipart => true}) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation_skil">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>	

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<article class="clearfix">
<div class="primary">
<section>
  <fieldset>
      <legend>Personal Information</legend>
      <div><%= f.label :first_name %> <%= non_editable_employee_field(:first_name)%></div>
      <div><%= f.label :last_name %> <%= non_editable_employee_field(:last_name)%></div>
      <div><%= f.label :job_title %> <%= non_editable_employee_field(:job_title)%></div>
      <div><%= f.label :email %> <%= f.text_field :email %></div>
      <div><%= f.label :location %> <%= non_editable_employee_field(:location)%></div>	
  </fieldset>

  <fieldset>
      <legend>Skills</legend>
      <div id="skill-tags">
      	<%= render :partial => "skill_tag", :collection => @employee.skill_tags, :locals => {:form => f} %>
      </div>
 	  <%= link_to 'add skills','', :id => 'add-skill' %>
  </fieldset>
  <fieldset>
      <legend>Industry Experience</legend>
      <div><%= text_field_tag :industry_tags , @industry_tags_names, :class => "industry_tags tagautocomplete" %></div>
  </fieldset>
  
  <fieldset>
      <legend>Product Experience</legend>
      <div><%= text_field_tag :product_tags , @product_tags_names, :class => "product_tags tagautocomplete" %></div>
  </fieldset>
  
  <hr />
      <%= f.label "Upload your resume" %>
      <%= file_field_tag :resume %>
      <%= f.label "Upload your bio" %>
      <%= file_field_tag :bio %>
  </section>
  </div>
  <div class="secondary">
      <section>
      <fieldset>
      <h4><%= f.label :professional_information %></h4>
      <%= f.text_area :professional_info %>
      </fieldset>
      <fieldset>
          <h4><%= f.label 'Give / Gets' %></h4>
          <%= f.text_area :give_gets %>
      </fieldset>
      <fieldset>
          <h4><%= f.label :interesting_facts %></h4>
          <%= f.text_area :interesting_facts %>
      </fieldset>
    </section>
    <div class="submit"><%= f.submit %></div>
</div>
<% end %>
</article>

app/views/employees/_skill_tag.html.erb
<%= fields_for "employee[skill_tags]", skill_tag do |skill_tag_form| %>
  <div class="clearfix">
    <% stamp = Time.current.to_f.to_s.sub('.','') %>
    <span class="skill-tag-col">
        <%= label_tag "employee[skill_tags]['#{stamp}'][name]", "Name:" %> <%= text_field_tag "employee[skill_tags]['#{stamp}'][name]", skill_tag['name'],:class => "skill_tags tagautocomplete" %>
    </span>
    <span class="skill-tag-col">
        <span class="tag-rating-label">Rate:</span> <%= hidden_field_tag "employee[skill_tags]['#{stamp}'][rate]", skill_tag['rate'] %>
        <%= ratings_edit(skill_tag['rate']) %>
        <%= link_to 'remove','', :class => 'remove-skill' %>
    </span>
  </div>
<% end %>

app/views/employees/edit.html.erb
<%= javascript_include_tag 'skills.edit' %>
<h2>Editing employee</h2>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', root_path %>

app/views/employees/search.html.erb
<article class="searchresults clearfix">
<div class="primary">
    <h2>Search</h2>
    <p class="result-count">Your search for "<%= params[:query] %>" returned <%= pluralize @matches, 'result' %></p>
    <section>
        <%= form_tag search_path, :method => :get do %>
           <div class="searchbox">         
               <%= text_field_tag :query %>    
               <%= image_submit_tag 'btn.search.gif' %>
               
               <p class="browse-link arvo"><a href="/taggings/skill_tags_cloud">Browse our visual skills graph</a></p>
           </div>
        <% end %>
    </section>
    
    <h2>Refine Search</h2>
    <section>
		<h3>Skills</h3>
        <% @skills_filter.each do |skill| %>
		  <%=skill%> <%= check_box_tag "#{skill}", "#{skill}" %>
		<% end %>
		<h3>Locations</h3>  
		<% @locations_filter.each do |location| %>
		  <%=location%> <%= check_box_tag "#{location}", "#{location}" %>
		<% end %>      
		<h3>Products</h3>  
		<% @products_filter.each do |products| %>
		  <%=products%> <%= check_box_tag "#{products}", "#{products}" %>
		<% end %>
		<h3>Industry</h3>  
		<% @industry_filter.each do |industry| %>
		  <%=industry%> <%= check_box_tag "#{industry}", "#{industry}" %>
		<% end %>
    </section>
</div>

<div class="secondary">
    <h2>Search Results</h2>
	<% if @results %>
        <ul id="results">
            <% @results.each do |doc| %>
              <% if doc %>
              <li>  
                  <section class="profile clearfix">        
                      <%if doc['picture_url'] -%>
						  <%= link_to image_tag(doc['picture_url'], :size => "80x80", :class => "profile-img"), employee_path(doc) %>	
                      <% else -%>
                          <%= link_to image_tag("generic.profile.gif", :size => "80x80", :class => "profile-img", :alt => "No Image Found"), employee_path(doc) %>
                      <% end -%>
                        <ul>
                  	        <li><h3><%= employee_link(doc) %></h3></li>
          	        	    <% if doc['skill_tags'] %>
          	        	    <li>
          	        	        <%= doc['skill_tags'].map { |tag| tag.name }.join(', ') %>
          	        	    </li>
          	        	    <li>
          	        	        <%= params[:query] %> 
          	        	        <%= ratings_readonly(doc['skill_tags'].find { |skill| skill.name.downcase.eql? (params[:query].downcase) }.rate) %>
          	        	    </li>
          	        	    <% end %>
                        </ul>
                    </section>
              </li>
              <% end %>
            <% end %>
            <%= will_paginate @results %>
        </ul>
      <% else %>
        <p id="result-count">Your search for "<%= params[:query] %>" returned no results"</p>
      <% end %>
</div>
</article>

app/views/employees/show.html.erb
<script>
    var skill_tags = '{"rows":[ <% @employee.skill_tags.each_with_index do |tag,i| %> {"key": "<%=tag.name%>", "value": "<%=tag.rate%>"} <% if (i != @employee.skill_tags.length - 1) %> , <%end %> <% end %>]}';
</script>

<article>
  <p id="notice"><%= notice %></p>
  <div class="primary">
    <h2>Your Profile</h2>
    <section class="profile clearfix"> 
        <%if @employee.picture_url -%>
            <img src="<%= @employee.picture_url %>" width="80" height="80" class="profile-img" alt="<%= @employee.first_name %> <%= @employee.last_name %>" />
        <% else -%>
            <img src="/images/generic.profile.gif" width="80" height="80" class="profile-img" alt="No Image Found" />
        <% end -%>
        
      <h3><%= @employee.full_name %> // <%= @employee.job_title %></h3>
      <ul class="summary">
        <li><strong>Industry:</strong> <%= @employee.industry_tags_names %></li>
        <li><strong>Skills:</strong> <%= @employee.skill_tags_names %></li>
        <li><strong>Products:</strong> <%= @employee.product_tags_names %></li>
        <li><strong>Email:</strong> <%= @employee.email %></li>
        <li><strong>Location:</strong> <%= @employee.location %></li>
        <% if @employee.resume -%>
        <li><strong>Resume:</strong> <%= link_to "View Resume", resume_path(@employee), :class => 'attach' %></li>
        <% end -%>
        <% if @employee.bio -%>
        <li><strong>Bio:</strong> <%= link_to @employee.bio, bio_path(@employee), :class => 'attach' %></li>
        <% end -%>
      </ul>
      
      <div class="bullets">
      <h4>Professional Information</h4>
      <p><%= @employee.professional_info.html_safe if @employee.professional_info %></p>
      <h4>Give / Gets</h4>
      <p><%= @employee.give_gets.html_safe if @employee.give_gets %></p>
      <h4>Interesting Facts</h4>
      <p><%= @employee.interesting_facts.html_safe if @employee.interesting_facts %></p>
      </div>
      <% if current_user == @employee -%>
        <%= link_to 'Edit', edit_employee_path(@employee) %> |
      <% end -%>

      <%= link_to 'Back', root_path %> </section>
  </div>
  <div class="secondary">
    <h2>Your Skills</h2>
    <section class="skills-graph-container">
      <div id="skills-graph" class="employee"></div>
    </section>
    <% if (!@similar_employees.empty?) %>
    	<h2>People like You</h2>
	    <div class="clearfix">
	      <section class="twoup">	    
			<%if @similar_employees.first.picture_url -%>
				<%= link_to image_tag("#{@similar_employees.first.picture_url}", :size => "80x80", :class => "profile-img", :alt => "#{@similar_employees.first.first_name} #{@similar_employees.first.last_name}"), edit_employee_path(@similar_employees.first) %>
	        <% else -%>
				<%= link_to image_tag("generic.profile.gif", :size => "80x80", :class => "profile-img", :alt => "No Image Found"), employee_path(@similar_employees.first) %>
	        <% end -%>
	        <p><strong><%= @similar_employees.first.first_name %> <%= @similar_employees.first.last_name %></strong></p>
	        <p><%= @similar_employees.first.job_title %></p>
	      </section>
	      <% if (@similar_employees[1]) %>
	      <section class="twoup last">
			<%if @similar_employees[1].picture_url -%>
				<%= link_to image_tag("#{@similar_employees[1].picture_url}", :size => "80x80", :class => "profile-img", :alt => "#{@similar_employees[1].first_name} #{@similar_employees[1].last_name}"), edit_employee_path(@similar_employees[1]) %>
	        <% else -%>
				<%= link_to image_tag("generic.profile.gif", :size => "80x80", :class => "profile-img", :alt => "No Image Found"), employee_path(@similar_employees[1]) %>
	        <% end -%>
	        <p><strong><%= @similar_employees[1].first_name %> <%= @similar_employees[1].last_name %></strong></p>
	        <p><%= @similar_employees[1].job_title %></p>
	      </section>
		  <% end %>
	    </div>
    <% end %>
  </div>
</article>

app/views/employees/skill.html.erb
<article class="wide-right skill-summary clearfix">
<div class="primary">
    <h2>Top <%= @tag.upcase %></h2>
    <% for i in 0..7 #faking this for now %>    
    <section class="profile">
	    <img src="<%= current_user.picture_url %>" width="80" height="80" class="profile-img" alt="<%= current_user.first_name %> <%= current_user.last_name %>" />
            <ul class="summary">
        	    <li><h3><%= current_user.first_name %> <%= current_user.last_name %> // <%= current_user.job_title %></h3></li>
	        	<li>Skills: </li>
	        	<li>Products: </li>
	        	<li>Industry: <%= current_user.industry %></li>
            </ul>
  	</section>
  	<% end %>
  	<div class="pagination">
  	    Page: 1 2 3 4 5 6 7 8 9 10 next >>
  	</div>
</div>
<div class="secondary">
    <h2>Skills / <%= @tag.upcase %></h2>

    <section class="callout">
        <h2><%= link_to(@tag.upcase, "#") %></h2>
        <ul>
            <li>100 - 80 % (15)</li>
            <li>80 - 60 % (20)</li>
            <li>60 - 40 % (10)</li>
            <li>40 - 20 % (5)</li>
            <li>20 - 0 % (5)</li>
        </ul>
    </section>

    <h3>Interesting Facts</h3>
    <section>
        <h4><%= link_to("Skills","#") %></h4>
        <ul>
            <li>100% ruby - 90% java</li>
            <li>80% ruby - 10% .net</li>
            <li>70% ruby - 1% C#</li>
            <li>60% ruby - 5% flash</li>
            <li>50% ruby - 90% SQL</li>
            <li>40% ruby - 90% php</li>
            <li>10% ruby - 90% php</li>
        </ul>
    </section>
</div>
</article>

app/views/employees/skills.html.erb
<article class="">
<ul id="skills-cloud">
    <% @tag_cloud['rows'].each do |tag|
        percent = tag['value'] * 100 * 3
        p = percent.to_s
        styleString = 'width: ' + p + 'px; height: ' + p + 'px; -webkit-border-radius: ' + p + 'px; -moz-border-radius: ' + p + 'px; border-radius: ' + p + 'px; line-height: ' + p + 'px;' 
    %>
        <li style='<%=styleString%>'><a href="/taggings/skill_tags/<%=h tag['key'] %>"><%=h tag['key'] %></a></li>       
    <% end %>
</ul>

</article>