config/routes.rb
Skillsdatabase::Application.routes.draw do
  resources :employees, :except => ['index']

  match '/taggings/skill_tags_cloud', :to => "taggings#skill_tags_cloud"
  match '/taggings/skill_tags_cloud/:limit', :to => "taggings#skill_tags_cloud"

  match '/taggings/skill_tags_group_by_rate/:tag_name', :to => "taggings#skill_tags_group_by_rate"

  match '/taggings/count/:tags_type', :to => "taggings#tags_count"
  match '/taggings/autocomplete', :to => "taggings#autocomplete"

  match '/taggings/:tags_type/:tag_name' , :to => "taggings#tag_query", :constraints => {:tag_name => /[^\/]+/ }

  match '/employees/resume/:id', :to => "employees#resume", :as => 'resume'
  match '/employees/bio/:id', :to => "employees#bio", :as => 'bio'

  match '/auth/:provider/callback', :to => 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout
  match '/search', :to => 'employees#search'
  match '/refine', :to => 'employees#refine_search'

  match "/login", :to => "welcome#login"

  root :to => "welcome#index"

end

app/views/shared/_footer.html.erb
<footer>
    
</footer>

app/views/shared/_head.html.erb
    <meta name="description" content="Razorfish Skills Database">
    <meta name="author" content="">

    <!--  Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS : implied media="all" -->
    <%= stylesheet_link_tag "style" %>
    <%= stylesheet_link_tag "jquery-ui" %>
    <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Arvo:regular,italic,bold,bolditalic" %>


    <!-- All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -->
    <%= javascript_include_tag "libs/modernizr-1.6.min" %>

    <%= csrf_meta_tag %>

app/views/shared/_header.html.erb
<header>

<%= sign_in_out_link %>

<%#= link_to("Sign Out", signout_url, :class => 'signout-link') if current_user %>

<h1><%= link_to("Razorfish Skills Database", root_path) %></h1>

</header>

app/views/shared/_scripts.html.erb
    <!-- Javascript at the bottom for fast page loading -->

    <!-- Grab Google CDN's jQuery. fall back to local if necessary ## Commenting out for now
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.js" %>
    <script>!window.jQuery && document.write(unescape('%3Cscript src="/javascripts/libs/jquery-1.4.4.min.js"%3E%3C/script%3E'))</script>-->
    <%= javascript_include_tag "libs/jquery-1.4.4.min.js" %>
    

    <!-- libs -->
    <%= javascript_include_tag "libs/raphael" %>
    <%= javascript_include_tag "libs/jquery.isotope.min" %>

    <!-- scripts -->
    <%= javascript_include_tag "skills.common" %>
    <%= javascript_include_tag "jquery-ui-1.8.6.custom.min" %>


    <!--[if lt IE 7 ]>
    <%= javascript_include_tag "libs/dd_belatedpng" %>
    <script>DD_belatedPNG.fix('img, .png_bg'); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
    <![endif]-->